//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeterReaderWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int AccountId { get; set; }
        public Nullable<System.DateTime> MeterReadingDateTime { get; set; }
        public Nullable<int> MeterReadValue { get; set; }
    }
}
